# Generated by Django 5.0.6 on 2024-06-08 13:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(
                max_length=25,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator("^\\+(?:[0-9] ?){6,14}[0-9]$")
                ],
            ),
        ),
    ]
