# Generated by Django 5.0.6 on 2024-06-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="password",
            name="username",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="password",
            name="website",
            field=models.CharField(default=" ", max_length=100),
            preserve_default=False,
        ),
    ]
